name: Scala Release CI
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile plugin
      run: |
        cd plugin
        sbt test

    - name: Run plugin tests
      run: |
        cd test
        echo "; +test; exit" | sbt

    - name: Release
      env: # Or as an environment variable
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        eval `cat .secret-enc/env | openssl aes-256-cbc -a -d -md sha256 -k "$SECRET_KEY"`
        cd plugin
        sbt ci-release
